#!/bin/zsh
set -e
pushd ~/my-dotfiles/nix/nix-darwin
nvim flake.nix
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
darwin-rebuild switch --flake . &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(darwin-rebuild --list-generations | grep current)
git commit -am "$gen"
popd
