background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
    noise = 0.0117
}

input-field {
    monitor =
    size = 320, 64
    outline_thickness = 2
    outer_color = rgba(@ACCENT@ee)
    inner_color = rgba(@BASE@cc)
    font_color = rgba(@TEXT@ff)
    check_color = rgba(@BLUE@ee)
    fail_color = rgba(@RED@ee)
    placeholder_text = <i>Passphrase</i>
    fade_on_empty = false
    rounding = 12
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(@TEXT@ff)
    font_size = 72
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}
