prSections:
  - filters: is:open author:@me
    title: My Pull requests
  - filters: is:open review-requested:@me
    title: Review Requested
  - filters: is:open -author:@me -reviewed-by:@me
    title: PRs I can Review
  - filters: is:open 
    title: All Open PRs

theme:
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#eba0ac"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#eba0ac"
      secondary: "#45475a"
      faint: "#313244"

pager:
  diff: delta
