-- Theme is controlled by ~/.config/theme, which is generated by Nix
-- (nix/modules/home.nix). Change the `theme` variable there and run
-- `bins/switch` to propagate.
local theme_file = os.getenv("HOME") .. "/.config/theme"
local f = io.open(theme_file, "r")
local theme = "nord"
if f then
	theme = f:read("*l") or "nord"
	f:close()
end

return {
	{
		"nvim-lualine/lualine.nvim",
		event = "VeryLazy",
		opts = {
			options = {
				globalstatus = true,
			},
		},
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = theme == "catppuccin" and 1000 or nil,
		config = theme == "catppuccin" and function()
			require("catppuccin").setup({
				flavour = "mocha",
				transparent_background = true,
				float = {
					transparent = true,
					solid = false,
				},
			})
			vim.cmd.colorscheme("catppuccin-mocha")
		end or nil,
	},
	{
		"gbprod/nord.nvim",
		priority = theme == "nord" and 1000 or nil,
		config = theme == "nord" and function()
			require("nord").setup({})
			vim.cmd.colorscheme("nord")
		end or nil,
	},
	{
		"ellisonleao/gruvbox.nvim",
		priority = theme == "gruvbox" and 1000 or nil,
		config = theme == "gruvbox" and function()
			require("gruvbox").setup({
				transparent_mode = true,
			})
			vim.cmd.colorscheme("gruvbox")
		end or nil,
	},
	{
		"folke/todo-comments.nvim",
		event = { "BufReadPost", "BufNewFile", "BufWritePre" },
		dependencies = { "nvim-lua/plenary.nvim" },
		opts = {
			signs = false,
		},
	},
}
