#!/bin/bash

# Theme is controlled by ~/.config/theme, which is generated by Nix
# (nix/modules/home.nix). Change the `theme` variable there and run
# `bins/switch` to propagate.
export WHITE=0xffffffff

THEME=$(cat "$HOME/.config/theme" 2>/dev/null || echo "nord")
if [ "$THEME" = "catppuccin" ]; then
	export BAR_COLOR=0xff1e1e2e       # Catppuccin Mocha Base
	export ITEM_BG_COLOR=0xff313244   # Catppuccin Mocha Surface0
	export ACCENT_COLOR=0xff89b4fa    # Catppuccin Mocha Blue
else
	export BAR_COLOR=0xff2e3440  # Nord Polar Night Darkest
	export ITEM_BG_COLOR=0xff3b4252  # Nord Polar Night Dark
	export ACCENT_COLOR=0xff88c0d0  # Nord Frost Light
fi
